# -*- coding: utf-8 -*-
"""Project9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12F9YmjKDn9RDUdsW0g627eQNdh0CXln9

# NLP Project 9: Student Feedback Analysis

Step 1: Import Libraries
"""

import pandas as pd
import nltk
import matplotlib.pyplot as plt
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from textblob import TextBlob

from wordcloud import WordCloud

"""Step 2: Download NLTK Resources"""

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

"""Step 3: Create Student Feedback Dataset"""

feedback = {
    "Feedback": [
        "The faculty explains concepts very clearly.",
        "The syllabus is too lengthy.",
        "Practical sessions are very helpful.",
        "The classroom projector is not working properly.",
        "Assignments improve understanding.",
        "Too many assignments every week.",
        "Faculty is friendly and supportive.",
        "Need more industry-related projects.",
        "Lab equipment should be upgraded.",
        "Excellent teaching methods.",
        "Class timing should be more flexible.",
        "Notes provided are very useful.",
        "Need more interactive sessions.",
        "The course content is interesting.",
        "Placement training should start earlier."
    ]
}

df = pd.DataFrame(feedback)

df.head()

"""Step 4: Preprocess Text"""

nltk.download('punkt_tab')
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):

    text = text.lower()

    text = text.translate(str.maketrans('', '', string.punctuation))

    words = word_tokenize(text)

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

df["Processed_Feedback"] = df["Feedback"].apply(preprocess)

df.head()

"""Step 5: Sentiment Analysis"""

def get_sentiment(text):

    polarity = TextBlob(text).sentiment.polarity

    if polarity > 0:
        return "Positive"

    elif polarity < 0:
        return "Negative"

    else:
        return "Neutral"

df["Sentiment"] = df["Processed_Feedback"].apply(get_sentiment)

df

"""Step 6: Count Sentiments"""

sentiment_count = df["Sentiment"].value_counts()

print(sentiment_count)

"""Step 7: Plot Sentiment Distribution"""

plt.figure(figsize=(6,4))

sentiment_count.plot(kind='bar')

plt.title("Student Feedback Sentiment Analysis")

plt.xlabel("Sentiment")

plt.ylabel("Number of Feedbacks")

plt.show()

"""Step 8: Generate Word Cloud"""

text = " ".join(df["Processed_Feedback"])

wordcloud = WordCloud(width=900,
                      height=450,
                      background_color="white").generate(text)

plt.figure(figsize=(10,5))

plt.imshow(wordcloud)

plt.axis("off")

plt.show()

"""Step 9: Product Improvement Areas"""

negative_feedback = df[df["Sentiment"] == "Negative"]

print(negative_feedback[["Feedback"]])

"""Step 10: Improvement Suggestions"""

suggestions = [
    "Reduce syllabus overload where possible.",
    "Balance assignment workload.",
    "Upgrade classroom equipment.",
    "Improve laboratory facilities.",
    "Introduce more industry-based projects.",
    "Conduct interactive learning sessions.",
    "Start placement preparation earlier."
]

for i, suggestion in enumerate(suggestions, start=1):
    print(f"{i}. {suggestion}")

"""Step 11: Summary Statistics"""

positive = len(df[df["Sentiment"]=="Positive"])
negative = len(df[df["Sentiment"]=="Negative"])
neutral = len(df[df["Sentiment"]=="Neutral"])

print("Positive Feedback :", positive)
print("Negative Feedback :", negative)
print("Neutral Feedback  :", neutral)

